# Generated by Django 5.2.7 on 2025-12-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_siteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('line1', models.CharField(blank=True, default='', max_length=200)),
                ('line2', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=60)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='blogs.siteconfig')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
