# Generated by Django 5.2.7 on 2025-12-11 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_siteaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('meta_title', models.CharField(blank=True, default='', max_length=200)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages_meta', to='blogs.siteconfig')),
            ],
            options={
                'ordering': ['slug', 'id'],
                'unique_together': {('config', 'slug')},
            },
        ),
    ]
