# Generated by Django 5.2.7 on 2025-12-11 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_pagemeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemeta',
            name='slug',
            field=models.CharField(db_index=True, max_length=220, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_/-]+$', 'Enter a valid path using letters, numbers, underscores, hyphens, and slashes.')]),
        ),
    ]
