# Generated by Django 5.2.7 on 2025-12-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_homeabout_partnerlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeabout',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
