# Generated by Django 5.2.7 on 2025-12-15 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_aboutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Customer Portal', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, default='', max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='pages/portal/')),
                ('portal_url', models.URLField(blank=True, default='')),
                ('faq_category', models.CharField(blank=True, default='', max_length=200)),
                ('use_faq_points', models.BooleanField(default=True)),
                ('show_partners', models.BooleanField(default=True)),
                ('appstore_ios_url', models.URLField(blank=True, default='')),
                ('appstore_android_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Portal Page',
                'verbose_name_plural': 'Portal Page',
            },
        ),
        migrations.CreateModel(
            name='PortalFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='blogs.portalpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blogs.portalpage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
