# Generated by Django 5.2.7 on 2025-12-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0015_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body_html', models.TextField(blank=True, default='')),
                ('meta_title', models.CharField(blank=True, default='', max_length=200)),
                ('meta_description', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Page',
                'verbose_name_plural': 'Legal Pages',
                'ordering': ['slug', 'id'],
            },
        ),
    ]
