# Generated by Django 5.2.7 on 2025-12-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0015_servicebutton_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryItemProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Industry',
                'verbose_name_plural': 'Industries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.industryitem',),
        ),
        migrations.CreateModel(
            name='ServiceButtonProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Button',
                'verbose_name_plural': 'Buttons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.servicebutton',),
        ),
        migrations.CreateModel(
            name='ServiceOfferingProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Consulting Service',
                'verbose_name_plural': 'Consulting Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.serviceoffering',),
        ),
        migrations.CreateModel(
            name='SolutionConsultantProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Consultant',
                'verbose_name_plural': 'Consultants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.solutionconsultant',),
        ),
        migrations.CreateModel(
            name='SolutionImageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.solutionimage',),
        ),
        migrations.CreateModel(
            name='SolutionPageProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Solution Page',
                'verbose_name_plural': 'Solution Pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.solutionpage',),
        ),
        migrations.CreateModel(
            name='SolutionVideoProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resources.solutionvideo',),
        ),
    ]
