# Generated by Django 5.2.7 on 2025-12-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Claims', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='claims_hero/')),
                ('body_html', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
            ],
        ),
    ]
