# Generated by Django 5.2.7 on 2025-12-13 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_seed_consulting_buttons_industries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimspage',
            options={'verbose_name': 'Claims Page', 'verbose_name_plural': 'Claims Pages'},
        ),
        migrations.AlterModelOptions(
            name='industryitem',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Industry', 'verbose_name_plural': 'Industries'},
        ),
        migrations.AlterModelOptions(
            name='quotepage',
            options={'verbose_name': 'Quote Page', 'verbose_name_plural': 'Quote Pages'},
        ),
        migrations.AlterModelOptions(
            name='servicebutton',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Button', 'verbose_name_plural': 'Buttons'},
        ),
        migrations.AlterModelOptions(
            name='serviceoffering',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Consulting Service', 'verbose_name_plural': 'Consulting Services'},
        ),
        migrations.AlterModelOptions(
            name='solutionconsultant',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Consultant', 'verbose_name_plural': 'Consultants'},
        ),
        migrations.AlterModelOptions(
            name='solutionpage',
            options={'ordering': ['menu_order', 'title'], 'verbose_name': 'Solution Page', 'verbose_name_plural': 'Solution Pages'},
        ),
        migrations.AlterModelOptions(
            name='solutionvideo',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='industryitem',
            name='icon',
            field=models.ImageField(blank=True, help_text='Square icon (e.g., 64×64 PNG)', null=True, upload_to='industry_icons/'),
        ),
        migrations.AlterField(
            model_name='industryitem',
            name='name',
            field=models.CharField(help_text='Industry card title', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicebutton',
            name='label',
            field=models.CharField(help_text='Button text (e.g., “Learn more”)', max_length=120),
        ),
        migrations.AlterField(
            model_name='servicebutton',
            name='url',
            field=models.URLField(blank=True, help_text='Destination URL for the button'),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='description_html',
            field=models.TextField(blank=True, help_text='Main description for this service section'),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='learn_more_url',
            field=models.URLField(blank=True, help_text='Optional link for detailed page'),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='pricing_html',
            field=models.TextField(blank=True, help_text='Optional pricing/notes section'),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='schedule_url',
            field=models.URLField(blank=True, help_text='Optional scheduling link'),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='title',
            field=models.CharField(help_text='Service section title', max_length=200),
        ),
        migrations.AlterField(
            model_name='serviceoffering',
            name='upcoming_url',
            field=models.URLField(blank=True, help_text='Optional upcoming classes link'),
        ),
        migrations.AlterField(
            model_name='solutionconsultant',
            name='intro_html',
            field=models.TextField(blank=True, help_text='Short bio/intro shown with the consultant card'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='slug',
            field=models.CharField(blank=True, max_length=220, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9_/-]+$', 'Enter a valid path using letters, numbers, underscores, hyphens, and slashes.')]),
        ),
        migrations.AlterField(
            model_name='solutionvideo',
            name='description_html',
            field=models.TextField(blank=True, help_text='Short description for the video'),
        ),
        migrations.AlterField(
            model_name='solutionvideo',
            name='title',
            field=models.CharField(help_text='Video title', max_length=200),
        ),
        migrations.AlterField(
            model_name='solutionvideo',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Paste full YouTube URL (e.g., https://www.youtube.com/watch?v=...)'),
        ),
    ]
