# Generated by Django 5.2.7 on 2025-12-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_alter_claimspage_options_alter_industryitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebutton',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='service_docs/'),
        ),
    ]
