# Generated by Django 5.2.7 on 2025-12-13 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0015_servicebutton_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='solution_card_icons/')),
                ('body_html', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='resources.solutionpage')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['order', 'id'],
            },
        ),
    ]
