# Generated by Django 5.2.7 on 2025-12-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_solutionimage_is_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionpage',
            name='cards_intro_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='cards_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
