# Generated by Django 5.2.7 on 2025-12-15 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_solutionpage_cards_intro_html_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solutionpage',
            options={},
        ),
        migrations.CreateModel(
            name='SolutionPageButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='page_button_docs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_buttons', to='resources.solutionpage')),
            ],
            options={
                'verbose_name': 'Page Button',
                'verbose_name_plural': 'Page Buttons',
                'ordering': ['order', 'id'],
            },
        ),
    ]
