# Generated by Django 5.2.7 on 2025-12-08 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Community Outreach', max_length=200)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='community_hero/')),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonprofit_name', models.CharField(max_length=200)),
                ('years_established', models.CharField(blank=True, max_length=100)),
                ('areas_served', models.CharField(blank=True, max_length=200)),
                ('community_impact', models.TextField(blank=True)),
                ('your_name', models.CharField(blank=True, max_length=200)),
                ('your_email', models.EmailField(blank=True, max_length=254)),
                ('your_phone', models.CharField(blank=True, max_length=50)),
                ('relationship_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CommunitySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='community.communitypage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommunityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='community_items/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='community.communitysection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
