# Generated by Django 5.2.7 on 2025-12-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_remove_teammember_photo_url_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
